Traceback (most recent call last):
  File "/data/tki_agpdev/kevin/phd/aim1/UORCA/script_development/experiments/MCP/Basic_MCP_client.py", line 29, in <module>
    asyncio.run(client())
                ^^^^^^
NameError: name 'client' is not defined
Traceback (most recent call last):
  File "/data/tki_agpdev/kevin/phd/aim1/UORCA/script_development/experiments/MCP/Basic_MCP_server.py", line 22, in <module>
    async def chat(user_message: str) -> Any:
                                         ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[04/24/25 15:35:28] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
[04/24/25 15:35:30] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
[04/24/25 15:35:34] INFO     HTTP Request: POST                  _client.py:1740
                             https://api.openai.com/v1/chat/comp                
                             letions "HTTP/1.1 200 OK"                          
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
slurmstepd: error: *** JOB 55898428 ON pnod2-10-18 CANCELLED AT 2025-04-24T15:35:57 ***
[04/24/25 15:36:23] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
[04/24/25 15:36:24] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
[04/24/25 15:36:28] INFO     HTTP Request: POST                  _client.py:1740
                             https://api.openai.com/v1/chat/comp                
                             letions "HTTP/1.1 200 OK"                          
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
error: Failed to spawn: `basic_mcp_server.py`
  Caused by: No such file or directory (os error 2)
Traceback (most recent call last):
  File "/data/tki_agpdev/kevin/phd/aim1/UORCA/script_development/experiments/MCP/Basic_MCP_server.py", line 26, in <module>
    class ReverseInput(BaseModel):
                       ^^^^^^^^^
NameError: name 'BaseModel' is not defined
slurmstepd: error: *** JOB 55898457 ON pnod2-10-18 CANCELLED AT 2025-04-24T15:42:26 ***
[04/24/25 15:43:28] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
[04/24/25 15:43:30] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
[04/24/25 15:43:31] INFO     HTTP Request: POST                  _client.py:1740
                             https://api.openai.com/v1/chat/comp                
                             letions "HTTP/1.1 200 OK"                          
[04/24/25 15:43:32] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
slurmstepd: error: *** JOB 55898458 ON pnod2-10-18 CANCELLED AT 2025-04-24T15:43:43 ***
[04/24/25 15:44:12] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
[04/24/25 15:44:13] INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
                    INFO     Processing request of type            server.py:534
                             CallToolRequest                                    
[04/24/25 15:44:15] INFO     HTTP Request: POST                  _client.py:1740
                             https://api.openai.com/v1/chat/comp                
                             letions "HTTP/1.1 200 OK"                          
                    INFO     Processing request of type            server.py:534
                             ListToolsRequest                                   
error: Failed to spawn: `Basic_MCP_client.py`
  Caused by: No such file or directory (os error 2)
error: Failed to spawn: `Basic_MCP_client.py`
  Caused by: No such file or directory (os error 2)
error: Failed to spawn: `Basic_MCP_client.py`
  Caused by: No such file or directory (os error 2)
error: Failed to spawn: `Basic_MCP_client.py`
  Caused by: No such file or directory (os error 2)
